### ISSUE TITLE
Setup all-contributors bot

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/sandbag#10]
@all-contributors please add @gibboj for code & ideas

**Comment by vnugent** [comment]
@all-contributors please add @AntoineMarnat for code & idea

**Comment by vnugent** [comment]
@all-contributors please add @gibboj  for code & idea

**Comment by musoke** [comment]
This issue seems to be completed?

**Comment by vnugent** [comment]
It's done.  Thank you for going through our issues. It's helping me to do some much needed house keeping :)

**Comment by musoke** [comment]
No problem, I hope I'm not getting annoying.  I'm just looking through the project to see the status and if there's anything I can contribute.
