### ISSUE TITLE
Add support for conversion between grades

### ISSUE THREAD

**Issue by gibboj** [OpenBeta/sandbag#14]
Current: 
Conversion function exists, but is totally untested and unused

Expected: 
Throughly fix and test the conversion functionality between grading systems. 

Non-goal: 
Don't try to support converting between bouldering and routes, only within bouldering grades and within routes.

**Comment by DarrenZLew** [comment]
As mentioned in https://github.com/OpenBeta/open-tacos/issues/520, I can help look into this one if I could be assigned to it. Thanks.

**Comment by musoke** [comment]
Is this done in #47?

**Comment by vnugent** [comment]
Yes. The library supports US and French.
