### ISSUE TITLE
Grades below V0 not parsed as valid grades on VScale

### ISSUE THREAD

**Issue by johncalvinroberts** [OpenBeta/sandbag#146]
Hi, me again! I think I may have found another potential issue with this really awesome library you have created! Happy to close this one out if this is a known issue or expected behavior.

### Problem

* `VB`, `VB-`, `VB+` are not parsed as valid grades by `VScale.isType` or `VScale.getScore` -- it doesn't recognize the string value as a valid grade.
* Despite this, passing a raw score integer (e.g., `16`) to `VScale.getGrade` will indeed return `VB`.
* Also, parsing a Font grade and converting it to a score (e.g., `Font.getScore("2b+")`), then passing that returned value to vscale will also indeed return `VB`.

Stackblitz demo of the issue: [here](https://typescript-bypjjt.stackblitz.io)

### Proposed Solution

I think this may be an issue with the regex being used for parsing V Scale grades? So, potential solution would be to fix this Regex and write some tests.

**Comment by musoke** [comment]
fixed by #147
