### ISSUE TITLE
Automate version bump

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/sandbag#15]
## Problem: 
while creating a new tag/release will trigger a build and `npm publish` automatically, we still need to manually bump the version in package.json 

## Todo:
Add  an automated version bump action

https://github.com/marketplace/actions/automated-version-bump

**Comment by RishiKumarRay** [comment]
there many ways of bumping a version , which one of that you want to prefer?

**Comment by vnugent** [comment]
I'm using `phips28/gh-action-bump-version@master`  (PR #21 ), but the GH Action failed.

GH action: https://github.com/OpenBeta/sandbag/blob/develop/.github/workflows/publish.yml#L13
log: https://github.com/OpenBeta/sandbag/runs/5075837090?check_suite_focus=true

**Comment by vnugent** [comment]
This issue blocks: https://github.com/OpenBeta/sandbag/issues/18

**Comment by vnugent** [comment]
fixed in PR #31
