### ISSUE TITLE
Update "allowableConversionType" lists

### ISSUE THREAD

**Issue by Agilulfo** [OpenBeta/sandbag#175]
I've noticed that the list of "allowableConversionType" for the sport scales are not aligned.
Scale A might have Scale B as allowed conversion but not Viceversa. 
It looks like this was more of an oversight than an intentional result.

I'm assuming that the purpose for this variable was to prevent conversion between bouldering and sport grades. But maybe there is more to it.
Either way maybe there is some potential here for some refactoring and to apply the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle.

**Comment by musoke** [comment]
Yes, I agree that there is much room for improvement here...
